# Generated by Django 3.0.6 on 2020-05-24 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_auto_20200524_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='post',
            field=models.ForeignKey(default=26, on_delete=django.db.models.deletion.CASCADE, to='restapi.Post'),
            preserve_default=False,
        ),
    ]
