# Generated by Django 3.0.6 on 2020-05-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0010_review_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewcount',
            field=models.IntegerField(default=0),
        ),
    ]
