# Generated by Django 3.0.6 on 2020-06-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0012_post_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/no_image.png', null=True, upload_to='images'),
        ),
    ]
