# Generated by Django 3.0.6 on 2020-06-05 09:24

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0013_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='images/no_image.png', force_format=None, keep_meta=True, null=True, quality=80, size=[640, 420], upload_to='images'),
        ),
    ]
